### ISSUE TITLE
Issue with mergemaster -iU

### ISSUE THREAD

**Issue by wholroyd** [NextBSD-classic/NextBSD-classic#12]
I looked through the repo and Makefiles to come up with some steps that seemed to have worked for building a NextBSD machine.

https://gist.github.com/wholroyd/cc1a0ea943f58266bc23

I ran into an issue with the `mergemaster -iU` step (line 15 in the above Gist) with a message saying `make[3] don't know how to make sendmail` and ending with a fatal error almost immediately after running. I skipped that step and it appears to work just fine without it after a reboot back to multi-user mode. Although FreeBSD isn't my specialty and I have no clue what may be broken as a result of skipping it.

![nextbsd](https://cloud.githubusercontent.com/assets/147990/9611237/809d4c3e-50ac-11e5-8414-7d54c90b81b3.png)

**Comment by ghost** [comment]
Thanks. We'll look in to it and update when fixed.

**Comment by mattmacy** [comment]
@outbackdingo: any progress on this?

**Comment by ghost** [comment]
so mergemaster -Ui doesnt fail for me, i did notice that it prompts for
delete missing files in the beginning, sendmail and other being some if you
say yes it works fine

**Comment by mattmacy** [comment]
@wholroyd can you try again? 

Thanks

**Comment by fkr** [comment]
fwiw, with HEAD I can't reproduce this.

**Comment by fkr** [comment]
can't reproduce.

**Comment by wholroyd** [comment]
My git notifications went to an email account I don't actively monitor, I'll give this a shot again and report back.

**Comment by fkr** [comment]
ok, thanks!
