### ISSUE TITLE
Wishful Thinking on the Subject of the Future Selection of NeXTBSD's Package Manager

### ISSUE THREAD

**Issue by RandomDSdevel** [NextBSD-classic/NextBSD-classic#13]
If you're going to be importing a lot of the stuff from OS X's Darwin underpinnings, then I'd like to suggest that, in the future, you might want to take a look at [Homebrew](https://github.com/Homebrew/homebrew).  It's a third-party, free–and–open-source package manager for OS X/Darwin that I use quite regularly on OS X via Terminal, and it works great most of the time.  Anyway, I just thought that you might want to check that out.

**Comment by jordanhubbard** [comment]
No need for Homebrew - we already have the FreeBSD ports collection, which contains over 27,500 different packages.  Homebrew, MacPorts and Fink only exist because OS X does not have a ports collection. :)

**Comment by RandomDSdevel** [comment]
Oh, duh, right; carry on!
