### ISSUE TITLE
Launchd fails to start jobs when run by install disk

### ISSUE THREAD

**Issue by ghost** [NextBSD-classic/NextBSD-classic#2]
<img width="667" alt="screen shot 2015-08-14 at 5 44 53 pm" src="https://cloud.githubusercontent.com/assets/1276183/9287092/5cf77dc2-42ba-11e5-9fe1-45385878600f.png">

**Comment by ghost** [comment]
@jceel how far were you from being able to remove the dependency on UNIX sockets? I think some timing issue with /var is preventing it from working. The right solution is to simply not depend on the file system at that stage.

**Comment by mattmacy** [comment]
fixed as of 68cebd8
