### ISSUE TITLE
Launchd cannot start getty when fsck is needed

### ISSUE THREAD

**Issue by pkgdemon** [NextBSD-classic/NextBSD-classic#23]
If a UFS filesystem is dirty launchd jobs such as getty cannot start due to the read only file system.  
Adding fsck_y_enable="YES" to rc.conf does not work around this.  The only way to currently resolve that I know of is to boot single user mode, and run fsck.

**Comment by fkr** [comment]
Indeed. the other way is to jump into the loader prompt and set the init path to init (avoiding launchd for one boot)

set init_path=/sbin/init

**Comment by ghost** [comment]
Thats fine for NextBSD, however on the Hardened branch, its hard wired so
its not possible to do this.
The real fix it to get a proper launchd json plist for fsck on ufs systems.

**Comment by fkr** [comment]
full ack (I did not mean it as a fix, just as another work around). However I was also not aware of the hard wiring in the hardened branch (thanks for pointing that out).

**Comment by pkgdemon** [comment]
Creating a simple json plist to run the rc.d script seems to do the trick for me.

https://github.com/NextBSD/NextBSD/blob/NextBSD-CURRENT/etc/rc.d/fsck

"/etc/rc.d/fsck",
"start"

Is that a good workaround?  Are there plans to remove /etc/rc.d in the future?  Would it make sense to move the contents of the /etc/rc.d/fsck script into it's own place somewhere else, and have launchd start that?

**Comment by pkgdemon** [comment]
Nevermind I spoke to soon.  This appeared to work after I shut down improperly.  However upon subsequent attempts I found it does not correct the issue.

**Comment by pkgdemon** [comment]
Ok so this is really strange but I found a useful workaround to avoid needing automatic fsck for UFS.  The default install is supposed to enable journaling but it doesn't work.  I can fix this by booting into single user mode, and doing this:

tunefs -j disable /dev/ada0s1a
tunefs -j enable /dev/ada0s1a

The partition of course changes on an EFI, or other setups.  After this fsck is no longer needed when shutting down improperly.
