### ISSUE TITLE
executing launchd directly hangs

### ISSUE THREAD

**Issue by DanPartelly** [NextBSD-classic/NextBSD-classic#27]
Executing launchd directly results in printing the required "launchd: this program is not meant to be run directly" , the some additional info is printed and the program hangs. It requires a ctrl+c to return to tcsh shell prompt

**Comment by fkr** [comment]
thanks for the report. Actually launchd will exit after 30s. The code (line 198 launchd.c) calls DEBUG_EXIT, and DEBUG_EXIT is defined in launchd.h as follows:

```
#define DEBUG_EXIT(x) \
        do { \
                syslog(LOG_EMERG | LOG_CONSOLE, "%s(%d):  about to exit", __FUNCTION__, __LINE__); \
                sleep(30); \
                launchd_exit(x); \
        } while (0)
```

What is more annoying is, that DEBUG_EXIT spams all terminals. but that is a different topic.
Will close this issue.
