### ISSUE TITLE
pkg problem: Shared object "libssl.so.8" not found, required by "pkg"

### ISSUE THREAD

**Issue by ghost** [NextBSD-classic/NextBSD-classic#33]
Shared object "libssl.so.8" not found, required by "pkg"

The default install for nextbsd. 
try to get pkg update works, but show the error message.

**Comment by fkr** [comment]
thanks for the report. indeed the iso is still installing libssl.so.7 am checking this with @jordanhubbard, since he runs the autobuilder for the isos.

**Comment by zchee** [comment]
+1
Tried `ln -s /use/lib/libssl.so.7 /use/lib/libssl.so.8` also libcrypto.so, `pkg` works fine.
But when `git clone`, again occurred SSL error :(

**Comment by ghost** [comment]
This is resolved in the latest builds
