### ISSUE TITLE
add pthread_workqueue support

### ISSUE THREAD

**Issue by ghost** [NextBSD-classic/NextBSD-classic#5]
see https://reviews.freebsd.org/D3189

**Comment by kithrup** [comment]
Do you want me to just push the other block changes?   It applied cleanly, so I didn’t do anything more than just patch.

Sean.

**Comment by jordanhubbard** [comment]
Sure, it would be hard to break anything more right? ;-)

**Comment by ghost** [comment]
Sadly there is plenty more to break.

**Comment by ghost** [comment]
Did you look at the comments by 'theraven'?

-K

**Comment by ghost** [comment]
This is committed  and works for some definition of works. However, I'm seeing issues in jemalloc so I'm not going to commit the change to enable workqueues in libdispatch until I've tracked those down.

**Comment by mattmacy** [comment]
blindly enabled by @jordanhubbard and seems to be working OK - apparently actually 'fixing' the deadlock seen in asld
